### ISSUE TITLE
Not able to download devenv

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/devenv#35]
After downlaod ` curl -O https://raw.githubusercontent.com/getsentry/devenv/main/install-devenv.sh`

on running bash install-devenv.sh

getting this error 
![image](https://github.com/getsentry/devenv/assets/43654389/0ef8765d-b5bc-461c-abd6-85f62c87a331)

**Comment by joshuarli** [comment]
We only support macos x86_64 or arm64 for now - that's where `shasum` is from. I'll probably be adding debian-like support soon.
